### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by onlyzy9** [Metro1998/hppo-in-traffic-signal-control#2]
Maybe you don't update the code in 'PPO_family' and 'utils'.

There is no 'src.rl.PPO_revision' in your repo, which is imported in 'train_supplement_revision.py'

And some method used in 'train_supplement_revision.py' raised 'unresolved reference' error. I think it's included in 'utils.py', but there is only one method in this file.

So I think maybe you don't update the code in some file.

**Comment by Metro1998** [comment]
When i finish my internship, i will update, just in a few days. Sorry for the messy code.


-----原始邮件-----
发件人:yuzhao ***@***.***>
发送时间:2023-10-10 18:55:27 (星期二)
收件人: Metro1998/hppo-in-traffic-signal-control ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Metro1998/hppo-in-traffic-signal-control] import error (Issue #2)






Maybe you don't update the code in 'PPO_family' and 'utils'.

There is no 'src.rl.PPO_revision' in your repo, which is imported in 'train_supplement_revision.py'

And some method used in 'train_supplement_revision.py' raised 'unresolved reference' error. I think it's included in 'utils.py', but there is only one method in this file.

So I think maybe you don't update the code in some file.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>






骆皓青

Haoqing (Ludvik) Luo, Master Student

Institute of Intelligent Transportation Systems

College of Civil Engineering & Architecture

Zhejiang University

 

Phone: （+86）18888923234

Email: ***@***.***
