### ISSUE TITLE
作者大大，您好，您的HPPO代码实现给予了我很大的帮助，谢谢！然后我现在有点疑问是关于HPPO的：

### ISSUE THREAD

**Issue by xtpy** [Metro1998/hppo-in-traffic-signal-control#8]

**Comment by xtpy** [comment]
请问HPPO的连续动作是否一定是和离散动作一一绑定的？我目前想要做的就是actor网络分别输出四个离散动作和一个连续动作，但是这个连续动作只与其中一个离散动作有关，与其余三个无关，这样的话我该如何用HPPO思考这个问题，谢谢

**Comment by Metro1998** [comment]
不是一一绑定的，你这个情况的话。假设离散动作1与之后的连续动作绑定（其大小为n），那么在构建continuous actor的时候只需要包含n个head，并用离散动作1进行index。




-----原始邮件-----
发件人:xtpy ***@***.***>
发送时间:2024-05-14 16:19:50 (星期二)
收件人: Metro1998/hppo-in-traffic-signal-control ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Metro1998/hppo-in-traffic-signal-control] 作者大大，您好，您的HPPO代码实现给予了我很大的帮助，谢谢！然后我现在有点疑问是关于HPPO的： (Issue #8)






请问HPPO的连续动作是否一定是和离散动作一一绑定的？我目前想要做的就是actor网络分别输出四个离散动作和一个连续动作，但是这个连续动作只与其中一个离散动作有关，与其余三个无关，这样的话我该如何用HPPO思考这个问题，谢谢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>










骆皓青

Haoqing (Ludvik) Luo, Master Student

Institute of Intelligent Transportation Systems

College of Civil Engineering & Architecture

Zhejiang University

 

Phone: （+86）18888923234

Email: ***@***.***

**Comment by xtpy** [comment]
非常感谢您的回复，您的意思是假如我同时输出这五个动作（其中1个连续），离散网络输出比如00101，只有末尾这个动作1有连续参数，那么我只要这个动作通过索引绑定连续参数，其他动作可以不用绑定参数？
